version: '3.9'

services:
  postgres_database:
    container_name: postgres_database
    hostname: ${POSTGRES_HOST}
    image: postgres
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      PGDATA: /var/lib/postgresql/data/
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres_${NODE_ENV}:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - backend

  server:
    container_name: server
    ports:
      - ${PORT}:5000
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - NODE_ENV
    volumes:
      - ./:/var/www/backend
      - ./node_modules:/var/www/backend/node_modules
    restart: always
    command: bash ./start_app.sh ${NODE_ENV}
    links:
      - postgres_database:${POSTGRES_HOST}
    depends_on:
      - postgres_database
    networks:
      - backend

networks:
  backend:
