version: '3'

services:
  postgres_prod:
    container_name: postgres_prod
    hostname: postgres_prod
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - .env.database.prod
    volumes:
      - ../postgres_prod:/var/lib/postgresql
    restart: always
    networks:
      - prod

volumes:
  postgres_prod:

networks:
  prod:
    driver: bridge
