version: '3'

services:
  postgres_dev:
    container_name: postgres_dev
    hostname: postgres_dev
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - .env.database.dev
    volumes:
      - ../postgres_dev_db:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - dev

  backend_dev:
    container_name: backend_dev
    ports:
      - 5000:5000
    build:
      context: ../backend
      dockerfile: Dockerfile.dev
    volumes:
      - ../backend:/var/www/backend
      - ../backend/node_modules:/var/www/backend/node_modules
    restart: always
    links:
      - postgres_dev:postgres_dev
    depends_on:
      - postgres_dev
    networks:
      - dev

volumes:
  postgres_dev:

networks:
  dev:
